#!/usr/bin/env ruby
puts "Dur!"
if ARGV.first.nil?
  puts 'Dur!!!!!!!! Dur!! Dur needs file path'
  exit
end
file = ARGV.first
unless File.exist? file
  puts 'Dur!! Dur Sad. Dur cannot see file :('
  exit
end
file = ARGV.shift
puts "Dur! Dur! Dur Happy with file!!"

if ARGV.first.nil?
  puts 'Dur!!!!!!!! Dur!! Dur need to know what is file mime type??'
  exit
end
mimetype = ARGV.first
puts "Dur! Dur! Dur Happy about mime type #{mimetype}"
template = "url(data:__MIMETYPE__;charset=utf8;base64,__DATA__)"
data = File.read(file)
require 'base64'
encoded_data  = Base64.strict_encode64(data) # no line feeds if strict
puts ""
puts "Dur Make Base64 Encoded Data URI for you - you make Dur Happy"
2.times {
  puts "" 
}
puts template.gsub('__MIMETYPE__',mimetype).gsub('__DATA__',encoded_data)


